name: SokruSTAFF
version: '${project.version}'
main: sokru.sokrustaff.SokruSTAFF
api-version: '1.20'
commands:
  vanish:
    permission: Staff.vanish
    description: vanish
  unvanish:
    permission: Staff.vanish
    description: vanish

permissions:
  Staff.vanish:
    description: vanish
    default: op
    children:
      Staff.showvanished: true
